# Site settings
title: codelyzer
description: > # this means to ignore newlines until "baseurl:"
  codelyzer documentation. A linter for Angular.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codelyzer.com/" # the base hostname & protocol for your site
twitter_username: mgechev
github_username:  mgechev/codelyzer

# Build settings
markdown: kramdown
markdown_ext: md
exclude: [vendor]

page_gen:
  - data: rules
    template: rule
    name: ruleName
    dir: rules
